language: python

python:
  - 3.6

before_install:
  - python --version
  - pip --version
  - uname -a
  - lsb_release -a

install:
  - make data/manga-7443-12703-LINCUBE.fits
  - pip install -r requirements.txt
  - python setup.py install

script:
  - make pep8
  - pytest
